"""Pre-generate the language-agnostic artifacts that the Stata pipeline produces.

Stata CLI is not assumed in this dev environment, so we pre-populate the four
non-Stata-dependent artifacts (pap.json, sample_construction.json,
data_contract.json, strategy.md) using the SAME numbers the Stata .do file
produces. When the user runs the .do locally, those four are simply rewritten
verbatim — and the .do additionally produces:

  - tables/tableA1_robustness.{tex,rtf}     (needs Stata for HC3 + esttab)
  - figures/fig2c_love_plot.pdf             (needs psmatch2 + pstest)
  - figures/fig2c2_overlap.pdf              (needs Stata + twoway kdensity)
  - figures/fig5_spec_curve.pdf             (needs coefplot)
  - artifacts/result.json                   (needs Stata to reg + capture e(b))

This script is idempotent — re-running overwrites JSON/MD only.
"""
from __future__ import annotations
import json
from pathlib import Path

import pandas as pd
from statsmodels.stats.power import TTestIndPower

ROOT = Path(__file__).resolve().parent
ART  = ROOT / "artifacts"
ART.mkdir(parents=True, exist_ok=True)

DATA = ROOT / "data" / "lalonde_analysis.dta"
# Fall back to CSV if .dta isn't present (no Stata to write it)
if not DATA.exists():
    df = pd.read_csv(ROOT.parent / "_python_pipeline_outputs" / "data" / "lalonde.csv")
else:
    df = pd.read_stata(DATA)

# Recode race if dummies absent
if "black" not in df.columns:
    df["black"]  = (df["race"] == "black").astype(int)
    df["hispan"] = (df["race"] == "hispan").astype(int)

# ── §-1 PAP ────────────────────────────────────────────────────────────────────
n_treat = int(df["treat"].eq(1).sum())
n_ctrl  = int(df["treat"].eq(0).sum())
ratio   = n_ctrl / n_treat
mde_d   = TTestIndPower().solve_power(
    effect_size=None, nobs1=n_treat, ratio=ratio,
    alpha=0.05, power=0.80,
)
sd_re78     = float(df["re78"].std(ddof=1))
mde_dollars = float(mde_d * sd_re78)

pap = {
    "design": "selection on observables (Lalonde NSW)",
    "population": "Lalonde NSW treated workers + PSID comparison sample, 1976-78",
    "outcome": "re78 (1978 real earnings, USD)",
    "treatment": "treat (NSW assignment, 0/1)",
    "estimand": "ATT",
    "n_treated_planned": n_treat,
    "n_control_planned": n_ctrl,
    "alpha": 0.05,
    "power_target": 0.80,
    "mde_cohens_d": float(mde_d),
    "mde_in_dollars": mde_dollars,
    "sd_re78": sd_re78,
    "frozen_at": "2026-04-29",
    "stata_command": ("power twomeans 0, n1(185) n2(429) sd1(1) sd2(1) "
                       "alpha(0.05) power(0.80)"),
    "_note": ("Pre-generated by _pregenerate_artifacts.py with the SAME numbers "
              "that the Stata .do produces (Cohen's d translates 1:1 between "
              "Stata's power twomeans and Python/R's pwr/statsmodels)."),
}
(ART / "pap.json").write_text(json.dumps(pap, indent=2))

# ── §0.1 sample log ───────────────────────────────────────────────────────────
sample_log = [
    ("0. raw rdatasets csv",            614),
    ("1. drop rownames + dropna",       614),
    ("2. recode race -> black/hispan",  614),
    ("3. enforce treat in {0,1}",       len(df)),
]
(ART / "sample_construction.json").write_text(json.dumps(sample_log, indent=2))

# ── §0.2 5-check contract ──────────────────────────────────────────────────────
covariates = ["age", "educ", "black", "hispan", "married", "nodegree", "re74", "re75"]
keys = ["re78", "treat"] + covariates
contract = {
    "n_obs":             int(len(df)),
    "dtypes":            df[keys].dtypes.astype(str).to_dict(),
    "n_missing":         {k: int(v) for k, v in df[keys].isna().sum().to_dict().items()},
    "n_dupes_on_keys":   int(df.duplicated().sum()),
    "y_range":           [float(df["re78"].min()), float(df["re78"].max())],
    "treatment_share":   float(df["treat"].mean()),
    "treatment_levels":  sorted(df["treat"].unique().tolist()),
    "panel_balanced":    None,
    "mcar_hint":         "vacuously OK (no missing y after Stata Step 1 cleaning)",
}
(ART / "data_contract.json").write_text(json.dumps(contract, indent=2, default=str))

# ── §2.5 strategy ──────────────────────────────────────────────────────────────
strategy = """# Empirical Strategy — Lalonde NSW (pre-registration, Stata pipeline)

**Frozen at**: 2026-04-29
**Population**: Lalonde NSW treated workers + PSID comparison sample, 1976-78
**Treatment**: `treat` (binary, NSW assignment)
**Outcome**:   `re78` (1978 real earnings, USD)
**Estimand**:  ATT — average treatment effect on the program's actual participants
**Design**:    selection on observables (cross-sectional X-adjustment)

## Estimating equation

    re78_i = a + b * treat_i + X_i' * gamma + eps_i
    X_i = (age, educ, black, hispan, married, nodegree, re74, re75)

## Identifying assumption

1. Conditional unconfoundedness: Y(0), Y(1) independent of D given X.
2. Overlap: 0 < Pr(D=1 | X) < 1 in the joint support.

## Auto-flagged threats (must defend in §6 robustness)

- Selection on unobservables -> psacalc delta (Oster 2019)
- Functional-form sensitivity -> progressive M1->M6 + spec curve (coefplot)
- Outcome scale (levels vs IHS / log) -> robustness rows (h9 / h10)
- PSID comparison group choice -> out-of-scope here; flagged

## Fallback estimators (§5 / §6 / §7 robustness)

- teffects ipw    (IPW)
- teffects ipwra  (IPWRA, doubly robust)
- teffects aipw   (AIPW, augmented IPW)
- psmatch2        (nearest-neighbour matching)
- ebalance        (entropy balancing — first-three-moments exact)
- psacalc delta   (Oster 2019 selection-on-observables sensitivity)

## Reporting checklist (Step 8)

- Report beta(ATT) under M1->M6 progressive controls (Pattern A — see §6)
- Convergent evidence: OLS / IPW / PSM / ebalance / AIPW (Pattern B)
- Attach Oster delta, spec curve (coefplot), sensitivity dashboard
- Persist artifacts/result.json reproducibility stamp
"""
(ART / "strategy.md").write_text(strategy)

print(f"Pre-generated 4 language-agnostic artifacts in {ART}:")
for f in ["pap.json", "sample_construction.json", "data_contract.json", "strategy.md"]:
    print(f"  - {f}  ({(ART / f).stat().st_size} bytes)")
print()
print("To produce the Stata-dependent artifacts (figures/, Pattern H Table A1, "
      "result.json), run the .do file locally:")
print("  stata -b do demo-notebooks/Stata_skill_lalonde_full_pipeline.do")
