#!/usr/bin/env python3
"""Build a non-blocking audit report for vendored skill hygiene."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import skill_discovery


ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
DEFAULT_JSON = ROOT / "catalog" / "skill-audit.json"
DEFAULT_MARKDOWN = ROOT / "docs" / "SKILL_AUDIT.md"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def iter_skill_like_files() -> list[Path]:
    paths: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(SKILLS_DIR):
        dirnames[:] = skill_discovery.prune(dirnames)
        for filename in filenames:
            if filename.lower() == "skill.md":
                paths.append(Path(dirpath) / filename)
    # Same normalization-free sort key as build-catalog.py's iter_skill_files();
    # see the comment there for why a bare `sorted()` orders differently on a
    # Windows checkout. The two must stay in lockstep -- the audit and the
    # catalog are cross-checked, so a divergence here shows up as spurious
    # drift. TestCrossPlatformSkillOrdering asserts both against one walk.
    return sorted(paths, key=lambda path: path.relative_to(SKILLS_DIR).parts)


def _skip_leading_comment(lines: list[str]) -> list[str]:
    """Drop a leading HTML comment banner (vendored CoPaper.AI provenance banner)
    plus surrounding blank lines, so frontmatter after the banner is detected."""
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines) and lines[i].lstrip().startswith("<!--"):
        while i < len(lines) and "-->" not in lines[i]:
            i += 1
        i += 1  # move past the line containing -->
        while i < len(lines) and not lines[i].strip():
            i += 1
    return lines[i:]


def parse_frontmatter(text: str) -> dict[str, str]:
    lines = _skip_leading_comment(text.splitlines())
    if not lines or lines[0].strip() != "---":
        return {}
    end = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
    if end is None:
        return {}
    data: dict[str, str] = {}
    for line in lines[1:end]:
        if not line or line.startswith((" ", "\t", "-")):
            continue
        match = re.match(r"^([A-Za-z0-9_-]+):(?:\s*(.*))?$", line)
        if match:
            value = (match.group(2) or "").strip()
            data[match.group(1)] = value.strip("'\"")
    return data


def build_payload() -> dict[str, object]:
    records: list[dict[str, object]] = []
    name_to_paths: defaultdict[str, list[str]] = defaultdict(list)

    for path in iter_skill_like_files():
        text = read_text(path)
        frontmatter = parse_frontmatter(text)
        exact_case = path.name == "SKILL.md"
        name = frontmatter.get("name") or path.parent.name
        record = {
            "path": rel(path),
            "collection": path.relative_to(SKILLS_DIR).parts[0],
            "exact_case": exact_case,
            "line_count": len(text.splitlines()),
            "has_frontmatter": bool(frontmatter),
            "has_name": bool(frontmatter.get("name")),
            "has_description": bool(frontmatter.get("description")),
            "name": name,
        }
        records.append(record)
        if frontmatter.get("name"):
            name_to_paths[frontmatter["name"]].append(rel(path))

    duplicate_names = {
        name: paths
        for name, paths in sorted(name_to_paths.items())
        if len(paths) > 1
    }

    return {
        "schema_version": "1.0",
        "generated_by": "scripts/build-skill-audit.py",
        "summary": {
            "skill_like_files": len(records),
            "exact_case_skill_files": sum(1 for record in records if record["exact_case"]),
            "non_exact_case_skill_files": sum(1 for record in records if not record["exact_case"]),
            "missing_frontmatter": sum(1 for record in records if not record["has_frontmatter"]),
            "missing_description": sum(1 for record in records if not record["has_description"]),
            "over_500_lines": sum(1 for record in records if record["line_count"] > 500),
            "duplicate_skill_names": len(duplicate_names),
        },
        "license": "hygiene audit only; see catalog/provenance.json for license metadata",
        "records": records,
        "duplicate_names": duplicate_names,
    }


def render_markdown(payload: dict[str, object]) -> str:
    summary = payload["summary"]
    records = payload["records"]
    duplicate_names = payload["duplicate_names"]

    lines = [
        "# Skill Hygiene Audit",
        "",
        "This file is generated by `scripts/build-skill-audit.py`. It is intentionally non-blocking because many issues come from preserved upstream vendor snapshots.",
        "",
        "## Summary",
        "",
        f"- Skill-like files: {summary['skill_like_files']}",
        f"- Exact-case `SKILL.md` files: {summary['exact_case_skill_files']}",
        f"- Non-exact-case skill files: {summary['non_exact_case_skill_files']}",
        f"- Missing YAML frontmatter: {summary['missing_frontmatter']}",
        f"- Missing descriptions: {summary['missing_description']}",
        f"- Over 500 lines: {summary['over_500_lines']}",
        f"- Duplicate skill names: {summary['duplicate_skill_names']}",
        "",
        "## Cleanup Targets",
        "",
        "| Type | Count | First examples |",
        "|---|---:|---|",
    ]

    targets = {
        "Missing frontmatter": [record for record in records if not record["has_frontmatter"]],
        "Missing description": [record for record in records if not record["has_description"]],
        "Over 500 lines": [record for record in records if record["line_count"] > 500],
        "Non-exact-case filename": [record for record in records if not record["exact_case"]],
    }
    for label, items in targets.items():
        preview = ", ".join(f"`{item['path']}`" for item in items[:8])
        lines.append(f"| {label} | {len(items)} | {preview} |")

    lines.extend(
        [
            "",
            "## Duplicate Skill Names",
            "",
            "| Skill name | Count | First paths |",
            "|---|---:|---|",
        ]
    )
    for name, paths in list(duplicate_names.items())[:80]:
        preview = ", ".join(f"`{path}`" for path in paths[:4])
        lines.append(f"| `{name}` | {len(paths)} | {preview} |")
    return "\n".join(lines).rstrip() + "\n"


def write_outputs(payload: dict[str, object], json_path: Path, markdown_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown(payload), encoding="utf-8")


def check_outputs(payload: dict[str, object], json_path: Path, markdown_path: Path) -> int:
    expected_json = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    expected_markdown = render_markdown(payload)
    failures: list[str] = []
    if not json_path.exists() or json_path.read_text(encoding="utf-8") != expected_json:
        failures.append(str(json_path.relative_to(ROOT)))
    if not markdown_path.exists() or markdown_path.read_text(encoding="utf-8") != expected_markdown:
        failures.append(str(markdown_path.relative_to(ROOT)))
    if failures:
        print("Skill audit outputs are stale. Regenerate with `make catalog`.", file=sys.stderr)
        for failure in failures:
            print(f"stale: {failure}", file=sys.stderr)
        return 1
    print("Skill audit outputs are current.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MARKDOWN)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = build_payload()
    if args.check:
        return check_outputs(payload, args.json, args.markdown)
    write_outputs(payload, args.json, args.markdown)
    print(f"Wrote {args.json.relative_to(ROOT)}")
    print(f"Wrote {args.markdown.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
