#!/usr/bin/env python3
"""Convert a link-check report into a markdown triage note for the failure path.

When the link-check workflows find broken URLs, a maintainer needs a single
page listing each failure with its source file, a guessed triage action
(replace / drop / mark), and the failure detail. This script reads the
committed JSON reports (catalog/external-link-check.json and
catalog/tools-link-check.json) and renders docs/LINK_TRIAGE.md.

Wired into the link-check workflows on failure: when the report has any
failures, the workflow runs this script and uploads the rendered triage note
as a workflow artifact; on pass the script is a no-op.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "LINK_TRIAGE.md"

EXTERNAL_REPORT = ROOT / "catalog" / "external-link-check.json"
TOOLS_REPORT = ROOT / "catalog" / "tools-link-check.json"


def render_failures(heading: str, report: Path) -> list[str]:
    if not report.exists():
        return [f"## {heading}\n\n_No report at `{report.relative_to(ROOT)}` (workflow did not run yet)._"]
    try:
        data = json.loads(report.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return [f"## {heading}\n\n_Report at `{report.relative_to(ROOT)}` is not valid JSON._"]
    failures = data.get("failures") if isinstance(data, dict) else None
    if not failures:
        return [f"## {heading}\n\n_Clean — no broken URLs._"]
    out = [f"## {heading}\n", f"_{len(failures)} broken URL(s):_\n", "| URL | Source / Tool | Status | Suggested action |", "|---|---|---:|---|"]
    for f in failures[:50]:
        url = f.get("url", "?")
        where = f.get("source") or f.get("tool") or f.get("path") or "—"
        status = f.get("status") or f.get("http_status") or "fail"
        action = "replace" if "404" in str(status) else "investigate"
        out.append(f"| `{url}` | `{where}` | {status} | {action} |")
    if len(failures) > 50:
        out.append(f"\n_…{len(failures) - 50} more failures in `{report.relative_to(ROOT)}`._")
    return out


def render() -> str:
    parts = [
        "# Link-check triage",
        "",
        "_Auto-generated by `scripts/build-link-triage.py` from the committed link-check reports._",
        "_Regenerate on link-check failure; freshness is NOT enforced on `make validate` (this file is a triage note, not a gate artifact)._",
        "",
    ]
    parts.extend(render_failures("Maintained docs (README / docs/)", EXTERNAL_REPORT))
    parts.append("")
    parts.extend(render_failures("Tools catalog (tools/tools.json)", TOOLS_REPORT))
    parts.append("")
    parts.append(
        "## How to use this\n\n"
        "1. **Replace** broken links where a working alternative exists (the tool moved, the paper got a new URL, etc.).\n"
        "2. **Drop** entries whose upstream is gone and no good replacement exists; retire from the catalog, do not re-add.\n"
        "3. **Mark** as `archived` if the upstream is permanently offline but the tool is still useful offline.\n"
    )
    return "\n".join(parts) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=OUT, help="output markdown path")
    args = parser.parse_args(argv)
    args.out.write_text(render(), encoding="utf-8")
    out = args.out.resolve()
    print(f"Wrote {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
