#!/usr/bin/env python3
"""Generate docs/RELEASE_NOTES.md — a machine-generated release snapshot.

docs/RELEASE.md asks maintainers to hand-assemble catalog stats, eval counts,
and quality-gate results at release time. This generator replaces that manual
step: it derives every number from the committed metadata (catalog, provenance,
eval-harness scenarios, benchmark tasks, tools catalog, rigor coverage), so the
snapshot is reproducible from a checkout and can never drift from the artifacts
it describes. Maintainers paste the snapshot into the GitHub release and add a
hand-written Highlights section on top.

Zero third-party dependencies (TOML via scripts/toml_compat.py). Mirrors the
build-*/--check pattern of the other generators.

With --html, also writes docs/releases/index.html — a single-file static page
that mirrors the same snapshot for the GitHub Pages site (so users browsing
the catalog don't need to open the .md). The HTML reuses the CSS variables
and layout tokens of docs/search.html so the two pages look like siblings.
"""

from __future__ import annotations

import argparse
import html
import importlib.util
import json
import sys
from pathlib import Path

import toml_compat

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "eval-harness" / "lib"))
from checks import AUTO_CHECKS  # noqa: E402


def _load_coverage_map():
    """The coverage map owns the method-family roster (METHOD_ORDER); reuse it
    so the snapshot and badge can never disagree with docs/RIGOR_COVERAGE.md."""
    path = ROOT / "scripts" / "build-coverage-map.py"
    spec = importlib.util.spec_from_file_location("aers_build_coverage_map", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


COVERAGE_MAP = _load_coverage_map()
CATALOG = ROOT / "catalog" / "skills.json"
PROVENANCE = ROOT / "catalog" / "provenance.json"
ENRICHED = ROOT / "catalog" / "skills-enriched.json"
TOOLS = ROOT / "tools" / "tools.json"
SCENARIO_DIR = ROOT / "eval-harness" / "scenarios"
TASK_DIR = ROOT / "benchmark" / "tasks"
OUT = ROOT / "docs" / "RELEASE_NOTES.md"
BADGE_OUT = ROOT / "docs" / "badges" / "rigor-coverage.json"
HTML_OUT = ROOT / "docs" / "releases" / "index.html"
CANONICAL_REPO_SLUG = (
    "brycewang-stanford/Auto-Empirical-Research-Skills"
)


def _repo_slug() -> str:
    """Return the canonical upstream slug for the 'GitHub releases' link.

    Deliberately a constant rather than `git remote get-url origin`. The
    generated HTML is committed and gated by `--check`, so any input that
    varies per clone makes the generator non-deterministic: a contributor
    working in a fork would rewrite the release links and trip the freshness
    gate for reasons unrelated to their change.

    The trade-off is that this constant does not follow the remote if the
    repository is ever renamed or transferred. CITATION.cff carries the same
    URL, and test_repo_slug_matches_citation_metadata pins the two together,
    so a move that updates the citation metadata will fail the suite here
    until this constant is updated too.
    """
    return CANONICAL_REPO_SLUG


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def scenario_stats() -> dict:
    n_scenarios = 0
    n_rubric = 0
    n_auto = 0
    categories: dict[str, int] = {}
    for path in sorted(SCENARIO_DIR.glob("*.toml")):
        with path.open("rb") as fh:
            s = toml_compat.load(fh)
        n_scenarios += 1
        categories[s.get("category", "?")] = categories.get(s.get("category", "?"), 0) + 1
        for item in s.get("rubric", []):
            n_rubric += 1
            if item.get("check") in AUTO_CHECKS:
                n_auto += 1
    return {
        "scenarios": n_scenarios,
        "rubric_items": n_rubric,
        "auto_checks": n_auto,
        "categories": categories,
    }


def benchmark_stats() -> dict:
    n_tasks = 0
    n_gold = 0
    n_required = 0
    for path in sorted(TASK_DIR.glob("*.toml")):
        with path.open("rb") as fh:
            t = toml_compat.load(fh)
        n_tasks += 1
        for g in t.get("gold", []):
            n_gold += 1
            if g.get("required"):
                n_required += 1
    return {"tasks": n_tasks, "gold_checks": n_gold, "required_checks": n_required}


def build() -> str:
    catalog = load_json(CATALOG)
    provenance = load_json(PROVENANCE)
    enriched = load_json(ENRICHED)
    tools = load_json(TOOLS)
    scen = scenario_stats()
    bench = benchmark_stats()

    summary = catalog.get("summary", {})
    methods = enriched.get("taxonomy", {}).get("method", {})
    licenses = provenance.get("summary", {}).get("licenses", {})

    lines = [
        "# Release Snapshot",
        "",
        "Generated by `scripts/build-release-notes.py` from committed metadata; do not edit by hand.",
        "Regenerate with `make catalog`. Freshness is enforced by `make validate`.",
        "",
        "Paste this snapshot into the GitHub release body and add a hand-written",
        "**Highlights** section on top (see [`RELEASE.md`](RELEASE.md)).",
        "",
        "## Catalog",
        "",
        f"- Top-level collections: **{summary.get('top_level_collections', '?')}**",
        f"- `SKILL.md` files: **{summary.get('skill_files', '?')}**",
        f"- Cataloged agent tools: **{len(tools.get('tools', []))}** ([`tools/CATALOG.md`](../tools/CATALOG.md))",
        "",
        "## Methodological rigor",
        "",
        f"- Method families in the coverage map: **{len(COVERAGE_MAP.METHOD_ORDER)}** ([`RIGOR_COVERAGE.md`](RIGOR_COVERAGE.md))",
        f"- Eval scenarios: **{scen['scenarios']}** "
        f"({scen['rubric_items']} rubric items, {scen['auto_checks']} auto-checkable) "
        "([`../eval-harness/`](../eval-harness/README.md))",
        f"- Benchmark tasks: **{bench['tasks']}** "
        f"({bench['gold_checks']} gold checks, {bench['required_checks']} required) "
        "([`../benchmark/`](../benchmark/README.md))",
        "",
        "### Method families (skills tagged)",
        "",
    ]
    for tag in sorted(methods, key=lambda k: (-methods[k], k)):
        lines.append(f"- `{tag}`: {methods[tag]}")
    lines += [
        "",
        "### Eval scenarios by category",
        "",
    ]
    for cat in sorted(scen["categories"]):
        lines.append(f"- `{cat}`: {scen['categories'][cat]}")
    lines += [
        "",
        "## License buckets",
        "",
    ]
    for name in sorted(licenses):
        lines.append(f"- {name}: {licenses[name]}")
    lines += [
        "",
        "## Quality gates",
        "",
        "- `make check` — catalog/provenance/audit/eval freshness, repo hygiene,",
        "  Paper-WorkFlow gates, stdlib unit tests, eval-harness lint + graded smoke,",
        "  and the strict numeric benchmark (reference-gold drift fails the build).",
        "- External links and OpenSSF Scorecard run on their scheduled workflows.",
        "",
    ]
    return "\n".join(lines)


def build_badge() -> str:
    """Shields.io endpoint JSON summarizing the rigor surface (README badge)."""
    scen = scenario_stats()
    bench = benchmark_stats()
    payload = {
        "schemaVersion": 1,
        "label": "rigor",
        "message": (
            f"{len(COVERAGE_MAP.METHOD_ORDER)} method families · "
            f"{bench['tasks']} benchmarks · {scen['scenarios']} evals"
        ),
        "color": "brightgreen",
    }
    return json.dumps(payload, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Markdown -> HTML for the GitHub-Pages release page
# ---------------------------------------------------------------------------
#
# We deliberately don't pull in a markdown library: the RELEASE_NOTES.md file
# has a small, well-defined grammar (H1/H2/H3 headings + bullets + inline code,
# bold, and links) and we already control its emission from `build()`. A 60-line
# parser keeps the script stdlib-only and avoids `pip install` drift.


def _md_inline(text: str) -> str:
    """Render inline markdown (`code`, **bold**, [link](href)).

    Order matters: escape HTML first so user-generated identifiers can't
    inject tags, then apply the inline substitutions. Backticks are matched
    greedily by splitting on them.
    """
    out = html.escape(text, quote=False)

    # Inline code: `code` -> <code>code</code>. We split on backticks so any
    # user-supplied content between them keeps its inner HTML-escaped form.
    if "`" in out:
        parts = out.split("`")
        rebuilt = []
        in_code = False
        for piece in parts:
            if in_code:
                rebuilt.append(f"<code>{piece}</code>")
            else:
                rebuilt.append(piece)
            in_code = not in_code
        out = "".join(rebuilt)

    # Bold: **text** -> <strong>text</strong>. Run AFTER code so backticked
    # content with literal asterisks isn't double-processed.
    import re

    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)

    # Links: [text](href). We accept both relative paths and absolute URLs.
    out = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        lambda m: f'<a href="{html.escape(m.group(2), quote=True)}">{m.group(1)}</a>',
        out,
    )
    return out


def _md_body_to_html(md: str) -> str:
    """Convert the RELEASE_NOTES.md body to HTML, split into H2 sections.

    Skips the top-of-file H1 (`# Release Snapshot`) and the 5-line preamble
    block — those move into the page header. Each subsequent `## Heading`
    becomes a `<section>` with its own anchor id derived from the heading
    text. The page is rendered top-down with newest first, so the same
    section ordering as the markdown.
    """
    lines = md.split("\n")
    # Drop the leading H1 line.
    while lines and not lines[0].startswith("# "):
        lines.pop(0)
    if lines and lines[0].startswith("# "):
        lines.pop(0)
    # Drop preamble until the first H2.
    while lines and not lines[0].startswith("## "):
        lines.pop(0)

    sections: list[tuple[str, list[str]]] = []
    current_title: str | None = None
    current_body: list[str] = []

    def _flush() -> None:
        if current_title is not None:
            sections.append((current_title, current_body))
        else:
            # Anything collected before the first H2 goes into a "Preview"
            # bucket so it isn't silently dropped.
            if current_body:
                sections.append(("Preview", current_body))

    for raw in lines:
        line = raw.rstrip()
        if line.startswith("## "):
            _flush()
            current_title = line[3:].strip()
            current_body = []
        else:
            current_body.append(line)
    _flush()

    parts: list[str] = []
    for title, body in sections:
        slug = html.escape(
            "".join(ch.lower() if ch.isalnum() else "-" for ch in title).strip("-")
            or "section"
        )
        parts.append(f'<section class="release-section" id="sec-{slug}">')
        parts.append(f"<h2>{html.escape(title)}</h2>")
        # Walk the body lines and emit small HTML chunks. We keep the same
        # bullet-grouping semantics as CommonMark: a blank line separates
        # paragraphs from lists.
        i = 0
        while i < len(body):
            line = body[i]
            stripped = line.strip()
            if not stripped:
                i += 1
                continue
            if stripped.startswith("- "):
                # Collect a contiguous run of bullets, including CommonMark
                # "lazy continuation" lines (lines that are indented but
                # don't start with `- `).
                items: list[str] = []
                while i < len(body):
                    raw_line = body[i]
                    line_strip = raw_line.strip()
                    if line_strip.startswith("- "):
                        items.append(line_strip[2:])
                        i += 1
                    elif line_strip == "":
                        # Blank line ends the list.
                        break
                    elif line_strip.startswith(("- ", "### ")) or line_strip.startswith("#"):
                        break
                    else:
                        # Treat as a continuation line for the previous bullet.
                        if items:
                            items[-1] = items[-1] + " " + line_strip
                        i += 1
                parts.append("<ul>")
                for item in items:
                    parts.append(f"<li>{_md_inline(item)}</li>")
                parts.append("</ul>")
                continue
            if stripped.startswith("### "):
                parts.append(f"<h3>{html.escape(stripped[4:])}</h3>")
                i += 1
                continue
            # Plain paragraph: take contiguous non-empty lines until the next
            # blank line or list/heading.
            para: list[str] = [stripped]
            i += 1
            while i < len(body) and body[i].strip() and not body[i].strip().startswith(("- ", "### ")):
                para.append(body[i].strip())
                i += 1
            parts.append(f"<p>{_md_inline(' '.join(para))}</p>")
        parts.append("</section>")
    return "\n".join(parts), sections


def _stats_summary_html() -> str:
    """Top-of-page at-a-glance card row derived from the same stats as the markdown."""
    catalog = load_json(CATALOG)
    enriched = load_json(ENRICHED)
    tools = load_json(TOOLS)
    scen = scenario_stats()
    bench = benchmark_stats()
    summary = catalog.get("summary", {})
    methods = enriched.get("taxonomy", {}).get("method", {})

    cards = [
        ("Collections", summary.get("top_level_collections", "?"), "Top-level skill folders"),
        ("Skills", summary.get("skill_files", "?"), "SKILL.md entries"),
        ("Method families", len(COVERAGE_MAP.METHOD_ORDER), "Distinct causal-inference families"),
        ("Eval scenarios", scen["scenarios"], f"{scen['auto_checks']} auto-checkable rubric items"),
        ("Benchmark tasks", bench["tasks"], f"{bench['required_checks']} required gold checks"),
        ("Tools", len(tools.get("tools", [])), "Agent tools cataloged"),
        ("Method-skills", sum(methods.values()), "Skills tagged with a method family"),
    ]
    out = ['<section class="stat-grid" aria-label="Snapshot at a glance">']
    for label, value, hint in cards:
        out.append(
            '<div class="stat-card">'
            f'<div class="stat-value">{html.escape(str(value))}</div>'
            f'<div class="stat-label">{html.escape(label)}</div>'
            f'<div class="stat-hint">{html.escape(hint)}</div>'
            "</div>"
        )
    out.append("</section>")
    return "\n".join(out)


def build_html() -> tuple[str, str]:
    """Build the static GitHub-Pages release page.

    Returns (html_body, html_content) where `html_body` is just the inner
    section markup (used by --check to detect drift) and `html_content`
    is the full page including the `<style>` shell.
    """
    md = build()
    body_html, sections = _md_body_to_html(md)
    stats_html = _stats_summary_html()
    repo_slug = _repo_slug()
    nav = []
    for title, _ in sections:
        slug = html.escape(
            "".join(ch.lower() if ch.isalnum() else "-" for ch in title).strip("-")
            or "section"
        )
        nav.append(f'<li><a href="#sec-{slug}">{html.escape(title)}</a></li>')

    css = """
    :root {
      color-scheme: light dark;
      --bg: #f7f7f4; --panel: #ffffff; --ink: #1f2933; --muted: #5f6b7a;
      --line: #d8d8d0; --accent: #0f766e; --warn: #9a3412; --good: #15803d;
      --chip: #eef2f1; --radius: 8px;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #111312; --panel: #181b1a; --ink: #edf2f0; --muted: #aab6b1;
        --line: #343a38; --accent: #5eead4; --warn: #fdba74; --good: #86efac;
        --chip: #20302c;
      }
    }
    * { box-sizing: border-box; }
    body { margin: 0; font: 15px/1.45 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; background: var(--bg); color: var(--ink); }
    header, main { width: min(1180px, calc(100% - 32px)); margin: 0 auto; }
    header { padding: 28px 0 18px; border-bottom: 1px solid var(--line); }
    .page-nav { display: flex; flex-wrap: wrap; gap: 12px 18px; align-items: center; margin-top: 12px; font-size: 13.5px; color: var(--muted); }
    .page-nav a { color: var(--accent); text-decoration: none; }
    .page-nav a:hover { text-decoration: underline; }
    .page-nav ul { display: flex; flex-wrap: wrap; gap: 6px 12px; margin: 0; padding: 0; list-style: none; }
    .page-nav li::before { content: "·"; margin-right: 8px; color: var(--line); }
    .page-nav li:first-child::before { content: ""; margin: 0; }
    h1 { margin: 0 0 6px; font-size: clamp(26px, 5vw, 42px); line-height: 1.05; }
    h2 { margin: 28px 0 10px; font-size: 22px; line-height: 1.2; border-bottom: 1px solid var(--line); padding-bottom: 4px; }
    h3 { margin: 20px 0 6px; font-size: 16px; color: var(--muted); }
    p { margin: 0 0 10px; color: var(--ink); }
    .lead { color: var(--muted); }
    .meta { color: var(--muted); font-size: 13px; margin-top: 4px; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
    ul { padding-left: 22px; margin: 0 0 12px; }
    li { margin: 2px 0; }
    .stat-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(170px, 1fr)); gap: 10px; margin: 18px 0 6px; }
    .stat-card { background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius); padding: 12px 14px; display: flex; flex-direction: column; gap: 4px; }
    .stat-value { font-size: 24px; font-weight: 600; line-height: 1.1; }
    .stat-label { font-size: 13px; color: var(--muted); }
    .stat-hint { font-size: 12px; color: var(--muted); }
    .release-section { background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius); padding: 16px 20px; margin: 18px 0; }
    .release-section h2 { margin-top: 0; border-bottom: none; padding-bottom: 0; }
    .release-section p:last-child, .release-section ul:last-child { margin-bottom: 0; }
    footer { width: min(1180px, calc(100% - 32px)); margin: 24px auto 36px; color: var(--muted); font-size: 13px; }
    @media (max-width: 720px) { .page-nav ul { width: 100%; } }
    """

    nav_list = "\n        ".join(nav) if nav else ""
    page = (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="utf-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "  <title>AERS Release Notes</title>\n"
        f"  <style>{css}</style>\n"
        "</head>\n"
        "<body>\n"
        "  <header>\n"
        "    <h1>AERS Release Notes</h1>\n"
        '    <p class="lead">Machine-generated snapshot of the catalog, eval, and benchmark state at every release. Paste this view into the GitHub release body and add a hand-written Highlights section on top.</p>\n'
        '    <div class="page-nav">\n'
        '      <span><a href="../search.html">&larr; Back to catalog</a></span>\n'
        '      <span><a href="https://github.com/' + html.escape(repo_slug, quote=True) + '/releases">GitHub releases &rarr;</a></span>\n'
        "    </div>\n"
        + (
            '    <nav class="page-nav" aria-label="Section navigation"><ul>\n'
            f'        {nav_list}\n'
            "    </ul></nav>\n"
            if nav_list
            else ""
        )
        + "  </header>\n"
        "  <main>\n"
        + stats_html
        + "\n"
        + body_html
        + "\n"
        + "  </main>\n"
        + "  <footer>\n"
        + f'    <p>Generated by <code>scripts/build-release-notes.py --html</code>. '
        + 'Refresh with <code>make catalog</code>. Markdown source: '
        + '<a href="../RELEASE_NOTES.md">docs/RELEASE_NOTES.md</a>.</p>\n'
        + "  </footer>\n"
        + "</body>\n"
        + "</html>\n"
    )
    return body_html, page


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed snapshot without rewriting it",
    )
    parser.add_argument(
        "--html",
        action="store_true",
        help="also render docs/releases/index.html (GitHub-Pages friendly mirror of RELEASE_NOTES.md)",
    )
    args = parser.parse_args(argv)

    content = build()
    badge = build_badge()
    html_body, html_page = (None, None)
    if args.html:
        html_body, html_page = build_html()

    if args.check:
        stale = []
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            stale.append("docs/RELEASE_NOTES.md")
        if not BADGE_OUT.exists() or BADGE_OUT.read_text(encoding="utf-8") != badge:
            stale.append("docs/badges/rigor-coverage.json")
        if args.html:
            if not HTML_OUT.exists() or HTML_OUT.read_text(encoding="utf-8") != html_page:
                stale.append("docs/releases/index.html")
        if stale:
            print(f"{' and '.join(stale)} stale. Regenerate with:", file=sys.stderr)
            print("  python3 scripts/build-release-notes.py" + (" --html" if args.html else ""), file=sys.stderr)
            return 1
        suffix = " and HTML" if args.html else ""
        print(f"docs/RELEASE_NOTES.md and rigor badge{suffix} are current.")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    BADGE_OUT.parent.mkdir(parents=True, exist_ok=True)
    BADGE_OUT.write_text(badge, encoding="utf-8")
    print(f"Wrote {BADGE_OUT.relative_to(ROOT)}")
    if args.html:
        HTML_OUT.parent.mkdir(parents=True, exist_ok=True)
        HTML_OUT.write_text(html_page, encoding="utf-8")
        print(f"Wrote {HTML_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
