#!/usr/bin/env python3
"""Five-minute "what does this repo do for me" walkthrough.

The whole point of AERS is hard to grasp from the README alone — there are
1,150 vendored skills across 69 collections, an executable rigor layer
(numeric benchmarks + behavioral evals), and an entry-point ``SKILL.md``
that registers the repo root as a single router skill.

This script is the on-ramp: it asks for nothing but the Python stdlib,
runs in <5 seconds, and produces a one-page "what just happened" report so
newcomers can decide whether to dig deeper. It does NOT touch the rigor
layer, evaluation harnesses, or vendored skill contents.

    python3 scripts/quickstart.py                # print the report
    python3 scripts/quickstart.py --markdown     # emit docs/QUICKSTART_REPORT.md
    python3 scripts/quickstart.py --json         # machine-readable summary
    python3 scripts/quickstart.py --task <id>    # simulate routing for a sample task
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog" / "skills.json"
PROVENANCE = ROOT / "catalog" / "provenance.json"
ENRICHED = ROOT / "catalog" / "skills-enriched.json"
RIGOR_DOC = ROOT / "docs" / "RIGOR_COVERAGE.md"
TRUST_DOC = ROOT / "docs" / "TRUST.md"
GREETING = "Auto-Empirical Research Skills (AERS) — five-minute tour"


# ────────────────────────────── data loaders ──────────────────────────────
def _read_json(path: Path):
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _load_catalog():
    raw = _read_json(CATALOG) or {}
    cols = raw.get("collections") or raw.get("vendored_skills") or []
    return cols, raw


def _provenance_map():
    raw = _read_json(PROVENANCE) or {}
    by_collection = {}
    if isinstance(raw, dict):
        # Support both {collections: [...]} and {skills: [...]}
        if isinstance(raw.get("collections"), list):
            for entry in raw["collections"]:
                if isinstance(entry, dict) and entry.get("id"):
                    by_collection[entry["id"]] = entry
        elif isinstance(raw.get("skills"), list):
            for entry in raw["skills"]:
                if isinstance(entry, dict) and entry.get("collection"):
                    by_collection[entry["collection"]] = entry
    elif isinstance(raw, list):
        for entry in raw:
            if isinstance(entry, dict) and entry.get("id"):
                by_collection[entry["id"]] = entry
    return by_collection


def _enriched_skills():
    raw = _read_json(ENRICHED) or {}
    return raw.get("skills") or raw.get("items") or []


def _tag_distribution():
    """Aggregate ``tags`` over every enriched skill so the report can show
    method/stage/language coverage. Falls back to the lighter catalog if the
    enriched catalog is missing.

    The enriched catalog stores tags as ``{method: [...], stage: [...],
    language: [...], topic: [...]}`` per skill (see scripts/build-catalog-enrich.py).
    """
    skills = _enriched_skills()
    if not skills:
        return {}, {}, {}
    methods = Counter()
    stages = Counter()
    languages = Counter()
    for sk in skills:
        if not isinstance(sk, dict):
            continue
        tags = sk.get("tags") or {}
        if not isinstance(tags, dict):
            continue
        for m in tags.get("method") or []:
            methods[m] += 1
        for s in tags.get("stage") or []:
            stages[s] += 1
        for lang in tags.get("language") or []:
            languages[lang] += 1
    return dict(methods), dict(stages), dict(languages)


def _method_families():
    """Parse the method-family roster out of RIGOR_COVERAGE.md.

    The doc is generated by ``scripts/build-coverage-map.py`` and contains a
    markdown table; we just need the first-column method-family names.
    """
    if not RIGOR_DOC.exists():
        return []
    families = []
    in_table = False
    for line in RIGOR_DOC.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("| Method family"):
            in_table = True
            continue
        if in_table:
            if not line.strip().startswith("|"):
                if families:
                    break
                continue
            if set(line.replace("|", "").strip()) <= {"-", " "}:
                continue
            family = line.split("|")[1].strip()
            if family:
                families.append(family)
    return families


# ────────────────────────────── routing demo ──────────────────────────────
# Static rules-of-thumb that mirror the routing intent of the catalog router.
# This is intentionally simple — the production router (``SKILL.md``) is the
# canonical source. The demo is here only to show newcomers *what a router
# does*; the precision of this dictionary is not part of the repo's
# correctness contract.
TASK_KEYWORDS = {
    "did": ["did", "difference in difference", "difference-in-differences",
            "staggered", "two-way fixed effects", "event study", "twfe",
            "平行趋势", "双重差分"],
    "iv":  ["instrumental", "2sls", "ivreg", "first stage", "first-stage",
            "工具变量", "弱工具"],
    "rd":  ["regression discontinuity", "rdrobust", "cutoff", "rd plot",
            "断点回归"],
    "scm": ["synthetic control", "synthdid", "donor pool",
            "合成控制"],
    "panel": ["panel", "fixed effects", "within estimator", "two-way fe",
              "面板数据", "固定效应"],
    "ml_ci": ["dml", "double machine learning", "meta-learner", "causal forest",
              "dragonnet", "bcf", "cate"],
    "review": ["rebuttal", "referee", "reviewer", "审稿", "replication",
               "replicate"],
    "write":  ["manuscript", "draft", "introduction", "abstract", "tikz",
               "写作", "introduction", "k head"],
    "lit":   ["literature review", "lit review", "systematic review",
              "openalex", "文献综述"],
    "de_aigc": ["de-aigc", "humanize", "de-slop", "去ai味", "去ai痕迹"],
}


def _route(task: str) -> list[str]:
    text = task.lower()
    hits = []
    for family, kws in TASK_KEYWORDS.items():
        if any(kw in text for kw in kws):
            hits.append(family)
    return hits or ["general"]


# ────────────────────────────── report assembly ──────────────────────────────
def _inventory(catalog) -> dict:
    cols = catalog
    n_skills = sum(c.get("skill_count", 0) for c in cols if isinstance(c, dict))
    methods, stages, languages = _tag_distribution()
    return {
        "collections": len(cols),
        "skills": n_skills,
        "languages_top": Counter(languages).most_common(5),
        "stages_top": Counter(stages).most_common(5),
        "methods_top": Counter(methods).most_common(5),
        "method_total_unique": len(methods),
    }


def _license_breakdown(provenance) -> dict:
    counts = Counter()
    for entry in provenance.values():
        if isinstance(entry, dict):
            counts[(entry.get("license") or "unknown")] += 1
    return dict(counts.most_common())


def _rigor_snapshot() -> dict:
    families = _method_families()
    return {
        "method_families": families,
        "n_families": len(families),
    }


def build_report() -> dict:
    catalog = _load_catalog()
    provenance = _provenance_map()
    inv = _inventory(catalog[0]) if isinstance(catalog, tuple) else _inventory(catalog)
    rigor = _rigor_snapshot()
    licenses = _license_breakdown(provenance)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "repo": "Auto-Empirical-Research-Skills",
        "root": str(ROOT),
        "inventory": inv,
        "rigor": rigor,
        "license_breakdown": licenses,
        "entry_points": [
            "SKILL.md (catalog router)",
            "README.md / README-zh-CN.md (overview)",
            "docs/search.html (faceted skill search)",
            "docs/SKILL_CATALOG.md (human-readable index)",
            "docs/CHOOSING_A_SKILL.md (goal→skill routing)",
            "docs/RIGOR_COVERAGE.md (method-coverage map)",
        ],
    }


def _bar(items, width=20):
    if not items:
        return ""
    max_v = max(v for _, v in items) or 1
    out = []
    for label, v in items:
        bar_len = max(1, round(width * v / max_v))
        out.append(f"  {label:<22} {'█' * bar_len} {v}")
    return "\n".join(out)


# ────────────────────────────── formatters ──────────────────────────────
def _print_human(report, task=None):
    inv = report["inventory"]
    rigor = report["rigor"]
    print(f"\n{GREETING}\n{'─' * len(GREETING)}")
    print(f"Generated: {report['generated_at']}\n")
    print("📦 What is in this repo (from catalog/skills.json):")
    print(f"  • {inv['collections']} collections · {inv['skills']} skills")
    print(f"  • {inv['method_total_unique']} distinct method tags")
    if inv["stages_top"]:
        print("  • Top research stages covered:")
        print(_bar(inv["stages_top"]))
    if inv["languages_top"]:
        print("  • Languages represented:")
        print(_bar(inv["languages_top"]))
    if inv["methods_top"]:
        print("  • Top method tags:")
        print(_bar(inv["methods_top"]))
    print()
    print("🛡️ Method rigor (from docs/RIGOR_COVERAGE.md):")
    if rigor["n_families"]:
        print(f"  • {rigor['n_families']} method families with closed rigor coverage")
        print("  • Sample:", ", ".join(rigor["method_families"][:6]), "…")
    else:
        print("  • RIGOR_COVERAGE.md not found — run `make catalog` to regenerate.")
    print()
    if report["license_breakdown"]:
        print("📜 License distribution (from catalog/provenance.json):")
        for lic, n in list(report["license_breakdown"].items())[:6]:
            print(f"  • {lic}: {n} collection(s)")
        print()
    print("🚪 Where to start:")
    for ep in report["entry_points"]:
        print(f"  • {ep}")
    if task:
        routed = _route(task)
        print()
        print(f"🧭 Routing demo for: '{task}'")
        print(f"  → matched families: {', '.join(routed)}")
        print("    (this is a static demo; the real router is SKILL.md)")
    print()
    print("Next: `make quickstart` for one command; `make catalog` to rebuild indexes;")
    print("or open docs/search.html to filter by method, stage, and language.")
    print()


def _write_markdown(report, out_path: Path):
    lines = [
        f"<!-- Generated by `python3 scripts/quickstart.py --markdown` on {report['generated_at']}. Do not edit by hand. -->",
        "",
        f"# {GREETING}",
        "",
        "A one-page, on-ramp report so newcomers can decide whether to dig into AERS.",
        "Run `python3 scripts/quickstart.py --markdown` to refresh after `make catalog`.",
        "",
        "## What is in this repo",
        "",
        f"- **{report['inventory']['collections']}** collections · **{report['inventory']['skills']}** skills",
        f"- **{report['inventory']['method_total_unique']}** distinct method tags",
        "",
        "### Top research stages",
        "",
    ]
    if report["inventory"]["stages_top"]:
        for label, v in report["inventory"]["stages_top"]:
            lines.append(f"- {label}: {v}")
    lines += ["", "### Languages represented", ""]
    if report["inventory"]["languages_top"]:
        for label, v in report["inventory"]["languages_top"]:
            lines.append(f"- {label}: {v}")
    lines += ["", "### Top method tags", ""]
    if report["inventory"]["methods_top"]:
        for label, v in report["inventory"]["methods_top"]:
            lines.append(f"- {label}: {v}")
    lines += [
        "",
        "## Rigor coverage",
        "",
        f"- **{report['rigor']['n_families']}** method families with closed rigor coverage",
    ]
    if report["rigor"]["method_families"]:
        lines += [
            "- Sample families: " + ", ".join(report["rigor"]["method_families"][:8]) + " …",
        ]
    lines += [
        "",
        "## License distribution",
        "",
    ]
    if report["license_breakdown"]:
        for lic, n in report["license_breakdown"].items():
            lines.append(f"- {lic}: {n} collection(s)")
    lines += [
        "",
        "## Where to start",
        "",
    ]
    for ep in report["entry_points"]:
        lines.append(f"- {ep}")
    lines += [
        "",
        "## Next steps",
        "",
        "- `make quickstart` — one command to print this tour again.",
        "- `make catalog` — regenerate indexes after adding or removing skills.",
        "- `make check` — full local quality gate before opening a PR.",
        "- `docs/search.html` — faceted skill search (method, stage, language, license).",
        "",
        "---",
        "",
        f"Generated by `scripts/quickstart.py` on {report['generated_at']}.",
        "Source of truth: `catalog/skills.json`, `catalog/provenance.json`, `docs/RIGOR_COVERAGE.md`.",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv=None):
    p = argparse.ArgumentParser(description="Five-minute AERS tour.")
    p.add_argument("--markdown", action="store_true",
                   help="Write a docs/QUICKSTART_REPORT.md snapshot.")
    p.add_argument("--json", action="store_true",
                   help="Emit a machine-readable JSON summary on stdout.")
    p.add_argument("--out", default="docs/QUICKSTART_REPORT.md",
                   help="Path for the markdown snapshot (default: docs/QUICKSTART_REPORT.md).")
    p.add_argument("--task", default=None,
                   help="Run the routing demo for a sample research task string.")
    args = p.parse_args(argv)

    report = build_report()
    if args.json:
        json.dump(report, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
    else:
        _print_human(report, task=args.task)

    if args.markdown:
        out_path = ROOT / args.out if not Path(args.out).is_absolute() else Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        _write_markdown(report, out_path)
        if not args.json:
            print(f"📝 Wrote markdown snapshot to {out_path}")


if __name__ == "__main__":
    main()